CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE contests (
    "Id" uuid NOT NULL,
    "Kind" text NOT NULL,
    "Title" text NOT NULL,
    "Subtitle" text,
    "Language" text NOT NULL,
    "Location" text NOT NULL,
    "StarsJoin" integer NOT NULL,
    "StarsWin" integer NOT NULL,
    "EndDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_contests" PRIMARY KEY ("Id")
);

CREATE TABLE documents (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "TextContent" text NOT NULL,
    "Language" text NOT NULL,
    CONSTRAINT "PK_documents" PRIMARY KEY ("Id")
);

CREATE TABLE products (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Price" integer NOT NULL,
    "ImageUrl" text,
    "Language" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_products" PRIMARY KEY ("Id")
);

CREATE TABLE profiles (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Role" text NOT NULL,
    "LanguageCode" text NOT NULL,
    "AvatarUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_profiles" PRIMARY KEY ("Id")
);

CREATE TABLE contest_questions (
    "Id" uuid NOT NULL,
    "ContestId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Stars" integer NOT NULL,
    "Multiple" boolean NOT NULL,
    "IsTextField" boolean NOT NULL,
    "CorrectTextAnswer" text,
    CONSTRAINT "PK_contest_questions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_contest_questions_contests_ContestId" FOREIGN KEY ("ContestId") REFERENCES contests ("Id") ON DELETE CASCADE
);

CREATE TABLE contest_answer_options (
    "Id" uuid NOT NULL,
    "QuestionId" uuid NOT NULL,
    "Text" text NOT NULL,
    "IsCorrect" boolean NOT NULL,
    CONSTRAINT "PK_contest_answer_options" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_contest_answer_options_contest_questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES contest_questions ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_contest_answer_options_QuestionId" ON contest_answer_options ("QuestionId");

CREATE INDEX "IX_contest_questions_ContestId" ON contest_questions ("ContestId");

CREATE INDEX "IX_contests_Language" ON contests ("Language");

CREATE INDEX "IX_documents_Language" ON documents ("Language");

CREATE INDEX "IX_products_Language" ON products ("Language");

CREATE INDEX "IX_profiles_LanguageCode" ON profiles ("LanguageCode");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251208104336_InitialSetup', '10.0.0');

COMMIT;

